name: Run Solar Data Collection Daily

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 8 PM IST (14:00 UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run Data Collection Script
        run: python main.py

      - name: Ensure Data File Exists
        run: |
          if [ ! -f all_data.csv ]; then
            echo "Creating an empty all_data.csv file..."
            touch all_data.csv
          fi

      - name: Store Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: collected-solar-data
          path: all_data.csv
